title: Don Easy
tagline: Serving Motion Picture

description: 
email: doneasy1@gmail.com
url: "https://doneasy1.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
author: Don Easy
share: true

date: 
update: 

categories: [connect, consult, contract]
permalink: :title/

# twitter_username:
# github_username:

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-relative-links

# for jekyll allow relative links in md 
relative_links:
  enabled: true
  collections: false

# site info, downloadable?
show_downloads: "false"
google_analytics: 
google-site-verification: 

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# https://github.com/jekyll/jekyll/pull/1291/commits/35b16f8f9d08cfca7ee6fb70b1c3ae4901d4ffa9
